version: '3.8'
services:
  app:
    build: .
    ports:
      - 8090:8090
    environment:
      - SPRING_PROFILES_ACTIVE=dev
#    depends_on:
#      - db
#  db:
#    image: mysql:8.0.28
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=myapp
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
